---
- name: maria_db is installed
  ansible.builtin.apt:
    name:
      - mariadb-server
    state: present
  # apt might be blocked by another installation (e.g. unattended upgrades)
  register: _results
  until: _results is not failed
  retries: 2
  delay: 60

- name: Nextcloud database and user (via shell) are created
  shell: |
    mysql -u root <<EOF
    CREATE DATABASE IF NOT EXISTS {{ db_name }};
    CREATE USER IF NOT EXISTS '{{ db_user }}'@'localhost' IDENTIFIED BY '{{ db_password }}';
    GRANT ALL PRIVILEGES ON {{ db_name }}.* TO '{{ db_user }}'@'localhost';
    FLUSH PRIVILEGES;
    EOF
  args:
    executable: /bin/bash
