---
- name: Nextcloud is downloaded
  ansible.builtin.get_url:
    url: "https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud_version }}.zip"
    dest: "/tmp/nextcloud.zip"

- name: Ensure target diretory "{{ nextcloud_dir }}" exists
  ansible.builtin.file:
    path: "{{ nextcloud_dir }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Nextcloud is extracted
  ansible.builtin.unarchive:
    src: "/tmp/nextcloud.zip"
    dest: "{{ nextcloud_dir }}"
    remote_src: yes

- name: Set permissions for Nextcloud directory
  file:
    path: "{{ nextcloud_dir }}"
    owner: www-data
    group: www-data
    recurse: yes

- name: Setup web server
  ansible.builtin.include_tasks: webserver.yml
  when: init_setup | bool

- name: Setup redis
  ansible.builtin.include_tasks: redis.yml
  when: init_setup | bool
