---
- name: Install nextcloud
  ansible.builtin.include_tasks: nextcloud.yml
  when: install_nextcloud | bool

- name: Setup web server
  ansible.builtin.include_tasks: webserver.yml
  when: init_setup | bool

- name: Setup redis
  ansible.builtin.include_tasks: redis.yml
  when: init_setup | bool

- name: Setup database
  ansible.builtin.include_tasks: database.yml
  when: init_setup | bool

- name: Create default nextcloud config file
  ansible.builtin.template:
    src: "nextcloud_default_config.php.j2"
    dest: "/var/www/nextcloud/config.php"
    owner: "www-data"
    group: "www-data"
    mode: "0640"
  notify: Restart Apache
  when: 
    - init_setup | bool
    - create_nextcloud_default_config | bool
