---
- name: Apache2 and php are installed
  ansible.builtin.apt:
    name:
      - apache2
      - libapache2-mod-php
      - php
      - php-mysql
      - php-gd
      - php-json
      - php-xml
      - php-mbstring
      - php-curl
      - php-zip
      - php-bz2
      - php-intl
      - php-bcmath
    update_cache: true
    state: present
  # apt might be blocked by another installation (e.g. unattended upgrades)
  register: _results
  until: _results is not failed
  retries: 2
  delay: 60

- name: Apache2 config for Nextcloud is created
  ansible.builtin.template:
    src: "nextcloud.conf.j2"
    dest: "/etc/apache2/sites-available/nextcloud.conf"
    owner: "root"
    group: "root"
    mode: "644"
  notify: Reload Apache2

- name: Disable default Apache2 site
  ansible.builtin.command: a2dissite 000-default.conf
  args:
    removes: /etc/apache2/sites-enabled/000-default.conf
  notify: Reload Apache2

- name: Enable Nextcloud site
  ansible.builtin.command: a2ensite nextcloud.conf
  args:
    creates: /etc/apache2/sites-enabled/nextcloud.conf
  notify: Reload Apache2

- name: Enable Apache2 modules (rewrite, headers, env, dir)
  ansible.builtin.command: a2enmod {{ item }}
  args:
    creates: "/etc/apache2/mod-enabled/{{ item }}.load"
  loop:
    - rewrite
    - headers
    - env
    - dir
  notify: Restart Apache2
