---
- name: Basic setup for Raspberry Pi
  hosts: all
  become: true
  gather_facts: true
  vars:
    upgrade_packages_clean_cache: true
    sudo_user: "kranjuli"
    sudo_user_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIO7CPfNf9BZJ+PUbsCCbTDD1UcEVwehs5RndBTJ43+U kranjuli@kranjuli-pi"

  tasks:
    - name: OS information
      ansible.builtin.debug:
        msg: "OS: {{ ansible_distribution }} - {{ ansible_facts['lsb']['release'] }}"

    - name: Upgrade OS packages
      ansible.builtin.apt:
        autoclean: true
        dpkg_options: 'force-confold,force-confdef'
        upgrade: dist
        update_cache: true
        lock_timeout: 600
      environment:
        DEBIAN_FRONTEND: noninteractive
        NEEDRESTART_MODE: a
      async: 900
      poll: 0
      register: _os_upgrade_job

    - name: Wait for upgrading of os packages to complete
      ansible.builtin.async_status:
        jid: "{{ _os_upgrade_job.ansible_job_id }}"
      register: _os_upgrade_status
      until: _os_upgrade_status.finished
      retries: 30
      delay: 30

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: false
      register: _reboot_required_file

    - name: Reboot is required
      ansible.builtin.debug:
        msg: "A reboot is required to complete the OS upgrade. The host will be rebooted now."
      when: _reboot_required_file.stat.exists
    
    - name: The host is rebooted
      ansible.builtin.reboot:
      when: _reboot_required_file.stat.exists

    - name: No longer required dependencies are removed
      ansible.builtin.apt:
        autoremove: true
        clean: true
      # apt might be blocked by another installation (e.g. unattended upgrades) so we want lots of retries
      register: _results
      until: _results is not failed
      retries: 2
      delay: 30

    - name: Install and configure unattended-upgrades
      ansible.builtin.apt:
        name: 
          - unattended-upgrades
          - apt-listchanges
        state: present
        update_cache: true
  
    - name: Configure unattended-upgrades to allow automatic reboot
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        content: |
          Unattended-Upgrade::Allowed-Origins {
            "${distro_id}:${distro_codename}-security";
            "${distro_id}:${distro_codename}-updates";
            "${distro_id}:${distro_codename}-proposed";
            "${distro_id}:${distro_codename}-backports";
          };
          Unattended-Upgrade::Automatic-Reboot "true";
          Unattended-Upgrade::Automatic-Reboot-Time "02:00";

    - name: Ensure unattended-upgrades service is enabled and started
      ansible.builtin.systemd:
        name: unattended-upgrades
        state: started
        enabled: true

    - name: Ensure apt-daily-upgrade.timer is enabled
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - apt-daily-upgrade.timer
        - apt-daily.timer

    - name: Remove default MOTD files
      ansible.builtin.file:
        path: /etc/motd
        state: absent
      loop:
        - /etc/motd
        - /etc/update-motd.d/10-help-text

    - name: Install figlet to display system information on login
      ansible.builtin.apt:
        name: figlet
        state: present
        update_cache: true

    - name: Delete apt cache
      ansible.builtin.file:
        path: /var/cache/apt/archives
        state: absent
      when: upgrade_packages_clean_cache

    - name: Create FIGlET banner script
      ansible.builtin.copy:
        dest: /etc/update-motd.d/01-banner
        mode: '0755'
        content: |
          #!/bin/bash
          echo -e "\e[32m"
          figlet -c "Welcome to {{ ansible_hostname }}"
          echo -e "\e[0m"
  
    - name: Create custom MOTD file
      ansible.builtin.copy:
        dest: /etc/update-motd.d/99-custom-pi-info
        mode: '0755'
        content: |
          #!/bin/bash
          echo '-----------------------------------------------------------------------------'
          echo "SYSTEM INFORMATION - $(date)"
          echo "OS:         {{ ansible_distribution }} - {{ ansible_facts['lsb']['release'] }}"
          echo "Kernel:     {{ ansible_kernel }}"
          echo "CPU Temp:   $(cat /sys/class/thermal/thermal_zone0/temp | awk '{print $1/1000}')"
          echo "Uptime:     $(uptime -p)"
          echo "Hostname:   $(hostname)"
          echo "IP Address: $(hostname -I | awk '{print $1}')"
          echo '-----------------------------------------------------------------------------'

    - name: Add sudo user on host
      ansible.builtin.user:
        name: "{{ sudo_user }}"
        groups: sudo
        append: true
        shell: /bin/bash
        create_home: true

    - name: Add sudo user SSH public key
      ansible.builtin.authorized_key:
        user: "{{ sudo_user }}"
        state: present
        key: "{{ sudo_user_ssh_public_key }}"

    - name: Ensure MOTD is not suppressed by hushlogin
      ansible.builtin.file:
        path: "/home/{{ sudo_user }}/.hushlogin"
        state: absent
