---
# handlers file for roles/nextcloud
- name: Restart Redis
  ansible.builtin.service:
    name: redis-server
    state: restarted

- name: Reload Apache2
  ansible.builtin.service:
    name: apache2
    state: reloaded

- name: Restart Apache2
  ansible.builtin.service:
    name: apache2
    state: restarted