---
# handlers file for roles/nextcloud
- name: Restart Redis
  ansible.builtin.service:
    name: redis-server
    state: restarted

- name: Reload Apache
  ansible.builtin.service:
    name: apache2
    state: reloaded
